### ISSUE TITLE
Supporting Sync Version

### ISSUE THREAD

**Issue by phandc** [lextudio/pysnmp#104]
### Is your feature request related to a problem? Please describe.

Hi, 
First of all, thank you for your hard work.
I have researched about Pysnmp recently. I was confused about the web browser suggesting two different versions of PySNMP util I read an announcement about Lex Studio taking over the project.
It is great when we utilize the power of asyncio in Python.
It would be great if we had a sync version too.until

### Describe the solution you'd like

It will be awesome if we have both sync and async versions. 
I could not find any documents about this at the moment.

**Comment by lextm** [comment]
No plan to work on this.
