### ISSUE TITLE
NotificationReceiver callback doesn't provide information about the generic trap types

### ISSUE THREAD

**Issue by robmool** [lextudio/pysnmp#105]
### Expected behavior

I expect that the NotificationReceiver through the callback function, would also provide information about the generic trap type (coldStart, warmStart, etc.) and sub-type. The information should not be limited to only var bindings.

The net-snmp tool 'snmptrapd' por example does provide all that information.

### Actual behavior

See example program below.

### Detailed steps

Example program:

from pysnmp.entity import engine, config
from pysnmp.carrier.asyncio.dgram import udp
from pysnmp.entity.rfc3413 import ntfrcv
from pysnmp.proto.rfc1902 import OctetString

snmpEngine = engine.SnmpEngine()

config.addTransport(
    snmpEngine,
    udp.domainName + (1,),
    udp.UdpTransport().openServerMode(('0.0.0.0', 9200))
)

config.addV1System(snmpEngine, 'trapr', 'public')

def cbFun(snmpEngine, stateReference, contextEngineId, contextName,
          varBinds, cbCtx):
    try:
        print("Received new trap message")
        for name, val in varBinds:
            print('%s = %s' % (name, val))
    except Exception as e:
        print('Exception 1: {}'.format(e))
        
ntfrcv.NotificationReceiver(snmpEngine, cbFun)
snmpEngine.transportDispatcher.jobStarted(1)  
snmpEngine.transportDispatcher.runDispatcher()

### Python package information

pysmi-lextudio 1.4.3, pysnmp-lextudio 6.2.1, snmpclitools-lextudio 0.7.0

### Operating system information

Linux Debian 12.6

### Python information

3.11.2

**Comment by lextm** [comment]
Pull requests are welcome, as my team has no plan to work on this in the near future. TRAP v2/INFORM have been the mainstream for decades.
