### ISSUE TITLE
Please enable bug reports for other lextudio/pysnmp-related repos

### ISSUE THREAD

**Issue by thesamesam** [lextudio/pysnmp#106]
We've adopted the lextudio forks of the pysnmp (thank you very much for taking them on) in Gentoo. We noticed that e.g. https://github.com/lextudio/pysmi doesn't have bug reports (the "Issues" tab) enabled. Would it be possible to turn it on? Thanks.

@mgorny noticed this in pysmi as Python 3.13 support broke: https://github.com/mgorny/pysmi/commit/1e4172ed888338e43f0aa341f5e86fcbba94dfd7#commitcomment-146152004.

**Comment by lextm** [comment]
All issues should be reported here, and that's well documented in the Readme file.

**Comment by thesamesam** [comment]
The bit at https://github.com/lextudio/pysmi?tab=readme-ov-file#how-to-get-pysmi kind of looks generic and like it might be a typo in linking to the wrong repo. In any case, it's kind of unexpected and counter-intuitive.  It's an unusual setup. But alright.
