### ISSUE TITLE
Error message encountered while sending v3 request with Privacy Type - DES

### ISSUE THREAD

**Issue by Leo05168** [lextudio/pysnmp#109]
### Expected behavior

SNMP manager(pysnmp) can send Get Request to SNMP Agent(DUT) with SNMP v3 account(auth-type: MD5, Priv-type: DES).

### Actual behavior

Got an error message from "cryptography" package.

![pysnmp error](https://github.com/user-attachments/assets/2ddd2235-5eb6-4bc4-9bfa-a2fb6ab63bc7)

### Detailed steps

1. Set SNMP Agent to SNMP v3 account(auth-type: MD5, Priv-type: DES)
2. SNMP manager(pysnmp) send Get Request to DUT with the same settings
3. Received the above error message

### Python package information

pysnmp 7.0.3, pysnmpcrypto 0.0.4, cryptography 43.0.1, pytest 8.3.2

### Operating system information

Debian

### Python information

python 3.12.5

### Relevant log output

```shell
File "/.venv/lib/python3.12/site-packages/pysnmpcrypto/des.py", line 44, in _cryptography_cipher
    algorithm=algorithms.TripleDES(key * 3),
              ^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/cryptography/utils.py", line 70, in __getattr__
    warnings.warn(obj.message, obj.warning_class, stacklevel=2)
cryptography.utils.CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
```

**Comment by Leo05168** [comment]
If I change the Priv-type from DES to AES-128, no errors will occur and a response will be received.

Or Update the des.py file as follows, the error can be temporarily solved, because "cryptography" seems to be removing TripleDES at version 48.0.0 in the future.
/.venv/lib/python3.12/site-packages/pysnmpcrypto/des.py

![image](https://github.com/user-attachments/assets/18401880-aafb-451b-8b30-f0df27f2c071)

**Comment by Leo05168** [comment]
Attached the changelog of 'cryptography".

![cryptography](https://github.com/user-attachments/assets/dc09a7cf-9cfc-4d77-bc01-ce6a48058319)

https://cryptography.io/en/latest/changelog/

**Comment by lextm** [comment]
Thanks. We are aware of this issue.

If you like, you can send us a pull request on pysnmpcrypto repo.

**Comment by Leo05168** [comment]
Hi Lextm,

I have issue a pull request, thanks.
[https://github.com/lextudio/pysnmpcrypto/pull/2](url)

**Comment by lextm** [comment]
Thanks. It has been merged and released.
