### ISSUE TITLE
snmpfwd Update?

### ISSUE THREAD

**Issue by DariusSG** [lextudio/pysnmp#110]
### Is your feature request related to a problem? Please describe.

snmpfwd has not been updated for usage against pysnmp version 6 and above.

It currently can only use 5.1.0 due to its dependency on asyncore.

### Describe the solution you'd like

An update to support the asyncio based pysnmp.

### Describe alternatives you've considered

I tried finding any SNMP V3 to V1/2 proxy but no such luck.

### Additional context

Is there any major bugs that makes it unusable or minor bugs to take note of? Does trap notifications work?

**Comment by lextm** [comment]
Pull requests are welcome.

We currently have no plan to update as no commercial customers use it.
