### ISSUE TITLE
ModuleNotFoundError: No module named 'pysnmp.entity.rfc3413.oneliner'

### ISSUE THREAD

**Issue by zdudic** [lextudio/pysnmp#112]
### Expected behavior

I expected that module can be imported. 
It's based on commit abce4e005e886551347509092e354371a1d66a6a

`>>> import pysnmp`
`>>> import pysnmp.entity.rfc3413`
`>>> import pysnmp.entity.rfc3413.oneliner`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`ModuleNotFoundError: No module named 'pysnmp.entity.rfc3413.oneliner'`

### Actual behavior

Based on this commit, oneliner should be present.

`commit abce4e005e886551347509092e354371a1d66a6a`
`Author: Lex Li <support@lextm.com>`
`Date:   Fri Mar 8 22:22:25 2024 -0500`

`    Added sync oneliner back.`

`A       pysnmp/entity/rfc3413/oneliner/__init__.py`
`A       pysnmp/entity/rfc3413/oneliner/cmdgen.py`
`A       pysnmp/entity/rfc3413/oneliner/ntforg.py`

### Detailed steps

Use pip to install pysnmp, go to python interactive mode and try to import module pysnmp.entity.rfc3413.oneliner.

### Python package information

pip     24.2

### Operating system information

Red Hat or Oracle Linux 7

### Python information

Python 3.10.4

**Comment by lextm** [comment]
Deleted again in release 6.2. No plan to bring them back.
