### ISSUE TITLE
pyasn1 0.6.1 removes pyasn1.compat.octets

### ISSUE THREAD

**Issue by hunterjm** [lextudio/pysnmp#114]
### Expected behavior

I expected a clean install to run.

### Actual behavior

But instead it throws module not found for `pyasn1.compat.octets`

### Detailed steps

1) Run a clean install
2) Profit

### Python package information

6.2.5

### Operating system information

Linux

### Python information

3.12.3

### Relevant log output

```shell
E   ModuleNotFoundError: No module named 'pyasn1.compat.octets'
```

See: https://github.com/pyasn1/pyasn1/pull/60

**Comment by cpackham-atlnz** [comment]
Snap #113

**Comment by hunterjm** [comment]
Beat me by a minute! Will close as duplicate.
