### ISSUE TITLE
AttributeError: module 'pysnmp.proto.api' has no attribute 'protoModules'

### ISSUE THREAD

**Issue by umair-zink** [lextudio/pysnmp#115]
### Expected behavior

I copied the simple snmp trap listener code and its not running with the latest pysnmp and pyasn1 libraries. 

### Actual behavior

AttributeError: module 'pysnmp.proto.api' has no attribute 'protoModules'

### Detailed steps

I copied and pasted the following code and its not running.

https://github.com/lextudio/pysnmp/blob/main/examples/v1arch/asyncio/manager/ntfrcv/listen-on-ipv4-and-ipv6-interfaces.py

### Python package information

sdf

### Operating system information

Linux Ubuntu

### Python information

3.12.6

**Comment by lextm** [comment]
The entire code base only contains a few `protoModules` in comments, so not sure how you triggered this issue.

Those comments have just been revised in the latest commit.
