### ISSUE TITLE
versions of things disambiguation 

### ISSUE THREAD

**Issue by CarlFK** [lextudio/pysnmp#119]
### Is your feature request related to a problem? Please describe.

Old and new confusing docs.

### Describe the solution you'd like

Let me open with thanking all those that are working on this project.  At best it is a complicated task, and given the history this project is burdened with, I can hardly imagine how hard it is to work on it.  I appreciate the work, and I am hoping my posts here make things better for those that come after me.  

I have been reading various docs, examples, guides, changelogs...
 
I understand there are many old things that are out of date, both code, examples, docs etc.
It would be good if this was addressed at the very top of the https://github.com/lextudio/pysnmp / README 

Something as simple as "This project contains obsolete information. Please refer to this page that defines what is and is not current: docs_disambiguation.rst - Hopefully some day all obsolete information will be removed, but that day has not happened yet."

After much reading,  it isn't clear what is recommended for a new project. 

I would assume  v3arch and SNMPv3 (which seem similar enough I think it is worth noting they are not related.)

But the 7.1 quick-start guide starts with SNMPv1and does not give a SNMPv3 example.
https://docs.lextudio.com/pysnmp/v7.1/quick-start#quick-start

changelog says "introducing v1arch hlapi"  which makes me question what is "new" - which I would expect is what I should be targeting.   which goes against what I would expect in version numbering - v3 sounds newer.    again, this is confusing and could be cleared up in a few words from someone who knows.

changelog says "does not break backward compatibility" but I suspect that only applies to ... I don;t really know, so I am guessing: 7.x?      It is clear from other docs there are incompatible changes, which is fine and expected, but the lack of clarity is confusing. 

There seems to be much more explanation about why things are they way they are, and much less about how things are and what I the user of this code should be doing.

what I have posted so far represents less than half of what I have found confusing as I try to understand what I should be doing.  My small set/get code might be working adequately for my needs, so I may not be looking at this project much in the near future.

**Comment by lextm** [comment]
Improving the documentation to a healthy state will be a lengthy process.

To begin with, we suggest starting with live test cases, particularly for beginners. These test cases are used to validate the current code base and can be found at https://github.com/lextudio/pysnmp/tree/main/tests/hlapi. Unlike articles or examples that may become outdated, the test cases are always up to date and reflect the correct functionality.

For users of version 4.x, we advise against rushing to the latest version. Adapting to too many changes all at once can be overwhelming. Instead, we recommend reviewing the upgrade guide at https://docs.lextudio.com/pysnmp/v7.1/upgrade. With each major release, we have taken steps to address issues in a more focused manner, ensuring that code migration remains manageable.

To help users navigate the changes introduced in different releases, we have begun hosting the documentation for versions 7.1, 7.0, 6.2, and 6.1 together. This allows users to compare the documentation side-by-side and gain a deeper understanding of any breaking changes.

The supporting resource will continue to be updated in the months and years to come.

**Comment by CarlFK** [comment]
```
# Old to new attribute mapping
deprecated_attributes = {
    "snmpUDPDomain": "SNMP_UDP_DOMAIN",
```
https://github.com/lextudio/pysnmp/blob/main/pysnmp/entity/config.py

**Comment by CarlFK** [comment]
@echo "  changes    to make an overview of all changed/added/deprecated items"

https://github.com/lextudio/pysnmp/blob/main/docs/Makefile#L44

**Comment by CarlFK** [comment]
Hmm... I am assuming the above are current for V7, but they might be so old they have been replaced by something else. 

some overview page that defines what is current and what is not would have been a great help.

**Comment by CarlFK** [comment]
> To begin with, we suggest starting with live test cases, particularly for beginners. >These test cases are used to validate the current code base and can be found at  https://github.com/lextudio/pysnmp/tree/main/tests/hlapi.

That is a great example of what is confusing:  there is v1arch, v3arch and I have no idea which one I should use or why.   

I looked at v1arch/.../test_slim.py 
import pytest 
but does running the tests teach me how to use it? (no)
does looking at the code tell me how I should use it?  maybe, but I would expect the code that tests many cases to test things that are not generally advisable. 

If this is really the best place to start, then put that in place of 
https://github.com/lextudio/pysnmp?tab=readme-ov-file#examples

**Comment by CarlFK** [comment]
looking at 
https://github.com/lextudio/pysnmp?tab=readme-ov-file#examples
```
from pysnmp.hlapi.v1arch.asyncio import *
        ObjectType(ObjectIdentity("SNMPv2-MIB", "sysDescr", 0)),
```
I am still unclear if I should start with v1arch or v3arch.

I know SNMPv2 is discouraged. I am sure I saw that as a note about some other example that used SNMPv1.  

I am not asking for a complete fixing of all the docs, I am asking for some guidance.  and not just me, so don't put it in this thread, put it on a "Start Here" page.

**Comment by lextm** [comment]
It appears that the issue #118 you originally brought up suggests that you were a user of release 4.x, but based on your recent inquiries related to this issue, it seems that you have limited or no experience with the project.

Our current focus is on assisting our commercial customers with migrating their projects, which makes it challenging to provide extensive support to other users.

You have the options to either wait for the documentation to become more comprehensive or gain hands-on experience by experimenting with the code.
