### ISSUE TITLE
Make pycryptodomex optional dependency

### ISSUE THREAD

**Issue by vanou** [lextudio/pysnmp#12]
(Same issue opened at [issue #40](https://github.com/pysnmp/pysnmp/issues/40) in `pysnmp/pysnmp` and redirected to `lextudio/pysnmp` on that issue)

At [etingof/pysnmp](https://github.com/etingof/pysnmp), there was work to make dependency on `pycryptodomex` optional [1]. That work intends moving from `pycryptodomex` to `pysnmpcrypto` (ultimately standard crypto module [`cryptography`](https://github.com/pyca/cryptography) of Python Cryptography Authority).

That work to make pycryptodomex optional is preferable because better support/maintenance from Python Cryptography Authority is expected.

[1] https://github.com/etingof/pysnmp/commit/24a7988766551038be2c65a33f10173a7a6d559d

**Comment by lextm** [comment]
Just tested but it does not seem to be finished as described.

More investigation is needed.

**Comment by lextm** [comment]
You can test `pysnmp-lextudio` 5.0.27, which contains the necessary changes.

**Comment by mattsb42-aws** [comment]
@lextm It's been a hot minute, and it sounds like you figured it out, but I'm curious what I missed. :)

**Comment by vanou** [comment]
@lextm Thanks for information! I'll test it.
