### ISSUE TITLE
An example of using Asyncio Dispatcher or processing an asynchronous Trap and Inform

### ISSUE THREAD

**Issue by James-aka-pr** [lextudio/pysnmp#123]
### Is your feature request related to a problem? Please describe.

Please write an example of using Asyncio Dispatcher or processing an asynchronous Trap and Inform.

### Describe the solution you'd like

I need an example of using Asyncio Dispatcher or handling asynchronous Trap and Inform.

**Comment by lextm** [comment]
What exactly do you need? Sending such to an SNMP device? Or receiving such from other devices? The main branch already has examples for the former.

**Comment by James-aka-pr** [comment]
I need receiving such from other devices.

**Comment by lextm** [comment]
[In this file](https://github.com/lextudio/pysnmp/blob/main/tests/manager_context.py) we define an SNMP manager that monitors incoming TRAP/INFORM messages during unit testing. You might refer to that and make necessary changes to your case.
