### ISSUE TITLE
snmpsim holds back newer pysnmp versions

### ISSUE THREAD

**Issue by svenpanne** [lextudio/pysnmp#124]
### Is your feature request related to a problem? Please describe.

Using snmpsim and pysnmp together results in pysnmp being tied to some 6.x.x version (6.2.6, to be exact). This is quite unfortunate, because one can't use the 7.x.x versions then.

### Describe the solution you'd like

Adapt snmpsim so that it works with recent pysnmp versions.

**Comment by lextm** [comment]
It is necessary to explain the purpose for requiring that, as ourselves currently don't know such a scenario.

Duplicate to #

**Comment by svenpanne** [comment]
Well, I hoped that the purpose is very obvious: If you have a project with both `snmpsim` and `pysnmp` in your virtual environment, you're stuck with the old `pysnmp` forever.

**Comment by lextm** [comment]
As maintainers, we expect

1. Users run snmpsim separately to emulate SNMP agents, where they don't really care what version of `pysnmp` is in that project.
2. When users need to select a specific version of `pysnmp`, they’re building their own SNMP applications, which shouldn't require snmpsim in the same project.

That's why we want to learn from you more details of your project. If you can explain more, we might reconsider the priority (currently set to low).

Besides, snmpsim won't forever stick to PySNMP 6.2, because now PySNMP has [lifecycle statements for all releases](https://github.com/lextudio/pysnmp/blob/main/SECURITY.md).

**Comment by svenpanne** [comment]
In our [project](https://github.com/Checkmk/checkmk) we have integration tests using `snmplib` and we have code using `pysnmp`. The virtual environment we use contains _both_ packages, and I have a hard time believing that this is a very uncommon setup. Giving every tiny tool its own venv/container/whatever to work around such dependency problems does not scale at all.

Regarding the lifecycles: AFAICT this would mean that every project which uses both packages will effectively be pinned to 6.2.6 for another 11 months, right? At least if `snmpsim` is not updated in the meantime.

**Comment by lextm** [comment]
Our current plan is to stabilize the API surface on the 7.1 branch. So, likely snmpsim will jump from PySNMP 6.2 directly to 7.1. We don't have an exact timeline for this transition at this moment, but must be ahead of PySNMP 6.2 end-of-life date.

However, if we had to support scenarios like yours, then we might have to ship at least three releases compatible to PySNMP 6.2, 7.0 and 7.1.

After some internal discussion, we decided to mark this scenario as not supported. We believe it is common to run multiple virtual environments for the same task. One example is we use 5 virtual environments to build PySNMP documentation via https://github.com/real-yfprojects/sphinx-polyversion.

**Comment by svenpanne** [comment]
Hmmm, that's very unfortunate that the scenario is suddenly declared as being unsupported. I still find it hard to believe that it's uncommon to use `snmpsim` and `pysnmp` in a single project in a single venv. Having separate venvs for every tiny tool is simply not an option for non-trivial projects, Checkmk for example pulls in >380 packages, ending up with >150 executables in the venv.

And if every release of 6.2, 7.0 and 7.1 breaks something API-wise, it would simply be good to have working snmpsim versions for each of those releases. You expect, after all, your library "customers" to adapt _their_ SW to those changes, so I guess you could do that for _your_ SW, too. :wink:

**Comment by lextm** [comment]
Our priority is to serve a group of commercial customers that depend on PySNMP/snmpsim, and none of them has such a requirement. So, we don't currently consider your request "common".

Another option you (or anyone in a similar situation) might consider is to fork snmpsim on your own and create the releases for your integration testing.

**Comment by lextm** [comment]
Just a quick update on this topic.

A few of our commercial customers are testing a private build that supports PySNMP 7.1. The test process is expected to finish in the summer before PySNMP 6.2 reaches the end of life.

You would need to sign a commercial contract to join the testing or wait till the new version is published in mid-Aug.
