### ISSUE TITLE
Please improve the documentation and versioning semantics for better user experience

### ISSUE THREAD

**Issue by RafaelFronteira** [lextudio/pysnmp#128]
### Is your feature request related to a problem? Please describe.

Hi,
First of all, thank you for your work!

Recently, I encountered some issues related to pysnmp updates.
The code I was developing was working perfectly until one day I got the following error:

**'ModuleNotFoundError: No module named 'pyasn1.compat.octets''**

I believe you've received several issues reporting this and possibly others related to breaking changes.
The problem I've had is that the documentation is quite fragmented. It took me a long time to find in the docs that the 7.0.x and 7.1.x releases are incompatible, which is unusual considering they're part of the same release series.

### Describe the solution you'd like

Here are my suggestions to improve the user experience:

**Documentation in key areas**

- Make it more highlighted both here on GitHub and in the documentation, the impact that new releases have on previous versions. If possible, this should be directly on the homepage.
- The link to [release updates](https://docs.lextudio.com/pysnmp/v7.1/upgrade) and [security policies](https://github.com/lextudio/pysnmp/blob/main/SECURITY.md) should be clearly displayed in the documentation and on GitHub, ideally on the home page for easy access.

**Improve versioning semantics**

- It's not expected for packages within the same version series ([major number](https://packaging.python.org/en/latest/discussions/versioning/#semantic-versioning)) to break with a minor update. So, If possible, updates with breaking changes should be _major_ version updates, not _minor_.

Sorry if I sound rude or anything, English is not my first language! I believe in the importance of this project and I would like to contribute to making it even better.

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
Duplicate to the pinned #113.

**Comment by RafaelFronteira** [comment]
Hi @lextm
The issue is not about #113 , it is a suggestion for improvement to the project documentation.

**Comment by lextm** [comment]
Thanks for sharing your thoughts. We had several rounds of internal discussions on the documentation, so below are some comments for your consideration.

## Version numbers

> It took me a long time to find in the docs that the 7.0.x and 7.1.x releases are incompatible, which is unusual considering they're part of the same release series.

It's very common (not unusual) in the industry to break something in minor releases, so we followed the rule of thumb to divide the changes into 7.0 and 7.1 releases.

> It's not expected for packages within the same version series ([major number](https://packaging.python.org/en/latest/discussions/versioning/#semantic-versioning)) to break with a minor update. So, If possible, updates with breaking changes should be _major_ version updates, not _minor_.

We don't plan to fully follow semantic versioning at this moment while the code base moves fast, or we will soon version 100 some time soon.

## Documentation Approach

> The problem I've had is that the documentation is quite fragmented.

We acknowledge this and have been working on this for a while now. But sadly, it is going to be a long journey.

> both here on GitHub and in the documentation

We will only focus on https://pysnmp.com. The GitHub contents will be kept to minimal in the coming months.

> The link to [release updates](https://docs.lextudio.com/pysnmp/v7.1/upgrade) and [security policies](https://github.com/lextudio/pysnmp/blob/main/SECURITY.md) should be clearly displayed in the documentation

We are still shuffling the contents and hope to stabilize the documentation site soon.

Before we reach the next milestone, you might want to

* Use a search engine with restrictions to better identify the information you might need. For example, "site:pysnmp.com" might help you get better results with Google.
* Or become a commercial customer of LeXtudio Inc. where our experts can answer your inquiries on the code base and docs more promptly.
