### ISSUE TITLE
can't reach of demo.pysnmp.com

### ISSUE THREAD

**Issue by rqx110** [lextudio/pysnmp#13]
![image](https://github.com/lextudio/pysnmp/assets/1829209/cb901473-ff34-4a82-9d59-5c69227eefeb)
with read community: public

**Comment by lextm** [comment]
Cannot reproduce this in Canada.

Note that port 1161, 2161, 3161 are no longer supported intentionally. I will edit the docs to reflect that change.

**Comment by rqx110** [comment]
access from China

**Comment by lextm** [comment]
No plan to further investigate if only users in China experience this. You can set up your own local SNMP agents instead.
