### ISSUE TITLE
Support multiple tables again in bulkWalkCmd

### ISSUE THREAD

**Issue by oriordan** [lextudio/pysnmp#131]
### Is your feature request related to a problem? Please describe.

Since pysnmp>=7.1.1 bulkWalkCmd only supports single table walks. This is due to the recent re-factoring of the function in https://github.com/lextudio/pysnmp/commit/f4be3d3371cc98a0ea290494e2439aae0d152f31. The commit message does not explain why this decision was made, but I assume it was intentional, hence this is not a bug but a lost feature.

### Describe the solution you'd like

Coming from pysnmp==4.4.12 the expectation is that bulkWalkCmd (bulkCmd in 4.x) can iterate trough multiple tables, until the longest table is exhausted. It should be up to the caller to deal with situation when table sizes are mismatching:

Pseudocode:
```python
>>> bulkWalkCmd("192.168.1.1", *("IF-MIB::ifName", "IF-MIB::ifSpeed"))
((('1.3.6.1.2.1.31.1.1.1.1.1', 'lo'), ('1.3.6.1.2.1.2.2.1.5.1', 10000000)),
(('1.3.6.1.2.1.31.1.1.1.1.4', 'sw0'), ('1.3.6.1.2.1.2.2.1.5.4', 2500000000)),
(('1.3.6.1.2.1.31.1.1.1.1.5', 'net2'), ('1.3.6.1.2.1.2.2.1.5.5', 0)),
(('1.3.6.1.2.1.31.1.1.1.1.6', 'net1'), ('1.3.6.1.2.1.2.2.1.5.6', 0)),
(('1.3.6.1.2.1.31.1.1.1.1.8', 'docker0'), ('1.3.6.1.2.1.2.2.1.5.8', 0)),
(('1.3.6.1.2.1.31.1.1.1.1.9', 'bnd0'), ('1.3.6.1.2.1.2.2.1.5.9', 1000000000)))
```

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
We intentionally updated the functionality of `nextCmd` and `bulkCmd` to be in line with other SNMP implementations and to correspond with the actual UDP packets transmitted over the network.

As a result, we changed the objective of `walkCmd` and `bulkWalkCmd` to ensure that only basic queries for a table or a few OIDs remain supported for users.

While we recognize that there may be scenarios where the old way is necessary, users have the flexibility to develop their versions of `bulkWalkCmdExtended` based on `bulkCmd`.
