### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by pieb** [lextudio/pysnmp#145]
### Expected behavior

I expected to be able to reproduce the example from the walk_cmd command documentation (https://docs.lextudio.com/pysnmp/v7.1/docs/hlapi/v1arch/asyncio/manager/cmdgen/walkcmd#pysnmp.hlapi.v1arch.asyncio.walk_cmd).

### Actual behavior

I get the following error "TypeError: object async_generator can't be used in 'await' expression". When I try the walk_cmd command without "await" in an "async for" loop, the command works.

### Detailed steps

The steps are,

### Python package information

7.1.13

### Operating system information

Ubuntu 22.04

### Python information

3.10.15

**Comment by lextm** [comment]
Most up-to-date examples are in unit test cases, https://github.com/lextudio/pysnmp/blob/main/tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_walk.py

**Comment by pieb** [comment]
Thanks for your response. I will look that.

**Comment by lextm** [comment]
Thanks for the report. Just updated the documentation and the fix will be live in a few minutes.
