### ISSUE TITLE
SNMPv2-SMI.py deprecation warnings

### ISSUE THREAD

**Issue by franxism** [lextudio/pysnmp#146]
### Expected behavior

When i run pysnmp based SNMP agent i got deprecation warnings (see attachment).

### Actual behavior

When i run pysnmp based SNMP agent i got deprecation warnings (see attachment).

### Detailed steps

When i run pysnmp based SNMP agent i got deprecation warnings (see attachment).

### Python package information

7.1.13

### Operating system information

SLES 15

### Python information

3.11

### Relevant log output

```shell
/usr/lib/python3.11/site-packages/pysnmp/smi/mibs/SNMPv2-SMI.py:1259: DeprecationWarning: isFixedLength is deprecated. Please use is_fixed_length instead.
  if impliedFlag or obj.isFixedLength():
/usr/lib/python3.11/site-packages/pysnmp/smi/mibs/SNMPv2-SMI.py:1231: DeprecationWarning: isFixedLength is deprecated. Please use is_fixed_length instead.
  elif obj.isFixedLength():
```

**Comment by lextm** [comment]
This is by design and preparation for the next major PySNMP release.
