### ISSUE TITLE
getMibSymbol() does not show real value associated with MIB

### ISSUE THREAD

**Issue by blusoldier001** [lextudio/pysnmp#15]
I'm experimenting with the .getMibSymbol() function, but it appears to not work for many more specific OIDs.

For example, this is a case where it works, where I use the OID for sysDescr.

```
>>>from pysnmp import builder
>>>from pysnmp.smi import view
>>>mibBuilder = builder.MibBuilder()
>>>mibViewController = view.MibViewController(mibBuilder)

>>>  objectIdentity = ObjectIdentity('1.3.6.1.2.1.1.1.0')
>>>  objectIdentity.resolveWithMib(mibViewController)
ObjectIdentity('1.3.6.1.2.1.1.1.0')
>>> objectIdentity.getMibSymbol() 
('SNMPv2-MIB', 'sysDescr', (<ObjectName value object, tagSet <TagSet object, tags 0:0:6>, payload [0]>,))
```

However, if I try to use the Oid for, say, Cisco hostName (1.3.6.1.4.1.9.2.1.3), this is what I get:
```
>>> objectIdentity = ObjectIdentity('1.3.6.1.4.1.9.2.1.3') 
>>> objectIdentity.resolveWithMib(mibView)
ObjectIdentity('1.3.6.1.4.1.9.2.1.3')
>>> objectIdentity.getMibSymbol()
('SNMPv2-SMI', 'enterprises', (<ObjectName value object, tagSet <TagSet object, tags 0:0:6>, payload [9.2.1.3]>,))
```

And while hostName is under the 'enterprises' umbrella, I'm a bit confused as to why pysnmp is more general in this case rather than be as specific as the case with sysDescr.

**Comment by lextm** [comment]
All SNMP libraries work in a similar way that only when the MIB documents are loaded, the objects defined in them can be resolved properly and the metadata are available.

You might find some hints from https://www.pysnmp.com/pysnmp/examples/smi/manager/browsing-mib-tree.html and the key to your case is to load Cisco MIB documents such as CISCO-SYS-MIB.

**Comment by blusoldier001** [comment]
Sorry to reopen this, but I think I'm still getting the issue.

```
>>> from pysnmp import *
>>> from pysnmp.smi import builder
>>> from pysnmp.smi import view
>>> from pysnmp.hlapi import *
>>> mibBuilder = builder.MibBuilder()
>>> mibViewController = view.MibViewController(mibBuilder)
>>> mibBuilder.loadModules("CISCO-SYS-MIB")
<pysnmp.smi.builder.MibBuilder object at 0x0000011CF0A06F90>
>>> objectIdentity = ObjectIdentity('1.3.6.1.4.1.9.2.1.3')
>>> objectIdentity.resolveWithMib(mibViewController)
ObjectIdentity('1.3.6.1.4.1.9.2.1.3')
>>> objectIdentity.getMibSymbol()
('SNMPv2-SMI', 'enterprises', (<ObjectName value object, tagSet <TagSet object, tags 0:0:6>, payload [9.2.1.3]>,))
```

**Comment by napstercc** [comment]
@lextm I'm having a similar issue. The output of my "varBinds" for the "walkCmd" is using 'SNMPv2-SMI' instead of my custom MIB.

**Comment by lextm** [comment]
Please enable MIB-related logging and debug further to see what is wrong with your custom MIB documents,

https://docs.lextudio.com/pysnmp/troubleshooting

If you find that the cause is not missing MIB document dependencies on your side, or PySNMP/PySMI version mismatch, you might create a new issue with more details.

Lock this thread as further comments without details are meaningless to pursue.
