### ISSUE TITLE
SNMPv3 Unknown Security Name error

### ISSUE THREAD

**Issue by V3n0nYm0uS** [lextudio/pysnmp#154]
### Expected behavior

I expected to just have my trap without error

### Actual behavior

i have some errors with my snmpv3 trap handler

### Detailed steps

I've set config.addV3User(
                self.engine, "userTest",
                config.usmHMACSHAAuthProtocol, "testAuth",
                config.usmDESPrivProtocol, "testPriv",
                securityName=v2c.OctetString(hexValue="800000020109840301"),
                securityEngineId=v2c.OctetString(hexValue="800000020109840301")
            )

### Python package information

6.2.6

### Operating system information

Linux 

### Python information

3.12.7

### Relevant log output

```shell
I have the following logtrace
prepareDataElements: SM failed, statusInformation {'errorIndication': UnknownSecurityName('Unknown SNMP security name encountered'), 'oid': (1, 3, 6, 1, 6, 3, 15, 1, 1, 3, 0), 'val': <Counter32 value object, tagSet <TagSet object, tags 64:0:1>, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts 0, 4294967295>>, payload [1]>, 'securityStateReference': 1872630, 'securityLevel': 1, 'contextEngineId': <SnmpEngineID value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint object, consts 5, 32>>, encoding iso-8859-1, payload [0x80004fb8053931...303834320001cd00]>, 'contextName': b'', 'msgUserName': <OctetString value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 32>>, encoding iso-8859-1, payload [testUser]>, 'maxSizeResponseScopedPDU': 65424}
```

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
TRAP v2 messages work in their special ways with SNMP v3, and we have test cases showing what you should expect,

https://github.com/lextudio/pysnmp/blob/v7.1.13/tests/hlapi/v3arch/asyncio/agent/ntforg/test_v3-trap.py

Note that the sender must disclose its engine ID, while the receiver must know that engine in advance,

https://github.com/lextudio/pysnmp/blob/v7.1.13/tests/manager_context.py#L51

**Comment by steven-douilliet** [comment]
See : https://github.com/etingof/pysnmp/issues/324
Engine IDs are designed to be unique within the set of communicating systems.
