### ISSUE TITLE
find code demo,snmp agent, support get,set,walk, trap, request parameter is custom OID

### ISSUE THREAD

**Issue by feng99** [lextudio/pysnmp#158]
### Describe the solution you'd like

seek code demo, the requirements of the implementation of snmp agent, support get,set,walk, trap

get,set support to pass custom OID, according to different OID, call different functions for processing.

thank you

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
Already covered in https://docs.lextudio.com/pysnmp/v7.1/examples/

👇

> The most reliable resources to see the API in action are the unit test cases under the tests folder in the [PySNMP GitHub repository](https://github.com/lextudio/pysnmp).
