### ISSUE TITLE
RuntimeError: await wasn't used with future when using pysnmp.hlapi.asyncio.cmdgen

### ISSUE THREAD

**Issue by anmcn** [lextudio/pysnmp#19]
The pysnmp.hlapi.asyncio.cmdgen functions appear to be broken, as this example demonstrates:
```python
import sys
import asyncio
from pysnmp.hlapi.asyncio import *

ipaddr, community = sys.argv[1:]

snmpEngine = SnmpEngine()

async def doit(varBinds):
    (errorIndication,
     errorStatus,
     errorIndex,
     varBindTable) = await bulkCmd(
        snmpEngine,
        CommunityData(community, mpModel=1),
        UdpTransportTarget((ipaddr, 161)),
        ContextData(),
        0, 10,
        *varBinds)

    if errorIndication:
        print(errorIndication)
    elif errorStatus:
        print('%s at %s' % (
            errorStatus.prettyPrint(),
            errorIndex and varBinds[int(errorIndex) - 1][0] or '?'
        )
              )
    else:
        for varBindRow in varBindTable:
            for varBind in varBindRow:
                print(' = '.join([x.prettyPrint() for x in varBind]))


asyncio.run(
    doit([
        ObjectType(ObjectIdentity('SNMPv2-MIB', 'system')),
    ])
)
```
```
$ python snmp_async_bulk.py 10.10.10.10 public
Traceback (most recent call last):
  File "snmp_async_bulk.py", line 37, in <module>
    loop.run_until_complete(
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "snmp_async_bulk.py", line 10, in run
    (errorIndication,
RuntimeError: await wasn't used with future
```
I believe the issue arises because the cmdgen functions return futures and consequently the use of the `async` keyword is inappropriate, as this turns them into coroutines. Alternatively, the functions could be changed to `return await future`, but this seems an unnecessary elaboration.

**Comment by lextm** [comment]
You might switch to the new `pysnmp.hlapi.asyncio.slim` wrapper, 

[examples/hlapi/asyncio/manager/cmdgen/v2c-bulk.py](https://github.com/lextudio/pysnmp/blob/v5.0.28/examples/hlapi/asyncio/manager/cmdgen/v2c-bulk.py)

**Comment by eLvErDe** [comment]
Hello,

Actually there is something wrong with @asyncio.coroutine patches to async def, that lead to an API change.

Here is what I have to do now to get it work on both version:

```python
result = await getCmd(
    engine,
    auth_data,
    transport_target,
    context_data,
    *targets,
)
if isawaitable(result):
    error_indication, error_status, error_index, variables = await result
else:
    error_indication, error_status, error_index, variables = result
```

This is definitely a **bug**.  All code from this module have the same broken pattern, it uses `return future` while it should use `return await future`.

I'll check and provided a PR.

**Comment by anmcn** [comment]
Confirming this fixes my issue. Thanks folks.

**Comment by lextm** [comment]
@spdkils If you only use v1/v2c, the slim API is more suitable and remains unchanged. For v3 operations, unfortunately the changes in 5.0.29 do break the code.

**Comment by spdkils** [comment]
It's fine, i'll just pin my previous versions to 0.28, and when I update, I'll push everything to 0.29+
Yes I'm on v3.
