### ISSUE TITLE
snmpget retry

### ISSUE THREAD

**Issue by sailone-leetcode** [lextudio/pysnmp#22]
using pysnmp cmd tools(https://www.pysnmp.com/snmpclitools/):
$ snmpget -v2c -c public demo.pynamp.com SNMPv2-MIB::sysDescr.0

when the demo.pynamp.com is not reachable , the request will be sent with increasing the request-id,
![263578156-c502eb36-e4ca-49e5-bd26-defed8dce6a6](https://github.com/lextudio/pysnmp/assets/77570450/d7d5ccf2-2579-4d90-85c6-8c6522fe4a24)

If the network transmission delay is greater than 1 second, the new request will sent endlessly.

Why don't we send the retry requests with the same id?

Thanks for reading!

**Comment by lextm** [comment]
Since Ilya passed away, we might not be able to learn why.

Note that if your goal is to have rock solid command line utilities to use for your daily work, the bits from NET-SNMP is still preferred (de facto standard). PySNMP command line tools are more like samples for your reference.

**Comment by sailone-leetcode** [comment]
sad to hear that.
thanks  for your reply.
