### ISSUE TITLE
getBulk response received by machine, but not picked up by PySNMP

### ISSUE THREAD

**Issue by daniel-fackrell-vasion** [lextudio/pysnmp#3]
I'm currently running 4.4.10 from PyPI (with the hlapi.asyncio backend) to collect information from printers, and found that we're able to receive individual get responses for some devices, but not BULK get responses, which time out. For other devices, we're able to get all of them without issue.

I've captured traffic for the target devices from my machine, and found that the responses come in to the machine, but somehow aren't recognized as responses to the requests that were sent. I can also hit these same OIDs with snmpbulkget at my Ubuntu command line.

I've added logging statements to see that we're getting to right before our bulkCmd() call, which raises a timeout error.

What should I do next for troubleshooting on this? Is there a better place to ask this?

Attached are two network traces, one showing a bulk get request (5) and response (6) that pysnmp caught, and the other showing a bulk get request (5) and response (6) that pysnmp missed and continued waiting for.

[troubleshooting.zip](https://github.com/lextudio/pysnmp/files/10450186/troubleshooting.zip)

**Comment by daniel-fackrell-vasion** [comment]
Please let me know if there's a better place to post this.

**Comment by lextm** [comment]
I will review the data and get back to you in a few days.

**Comment by lextm** [comment]
Indeed the packets look good. Can you follow the article to enable logging by adding the code snippet?

http://www.pysnmp.com/pysnmp/examples/#using-these-examples

``` python
from pysnmp import debug

debug.setLogger(debug.Debug('all'))
```

That should reveal all underlying activities in both succeeded and failed cases and we can compare and locate the culprit.

Note that I just reviewed all pending issues in the original repo and I believe similar cases were reported but not well investigated, so we might be able to see if a bug is there.

**Comment by guidocaffa** [comment]
Ey guys, same issue here. I’m having the same issue with some customer devices. For one device , a get request is completed and we get the data, but getBulk is failling, no data gathered…

As Daniel said, we are also using asyncio for multi threads. The problem with this is that the issue happens with devices in customer network and not In our local environment 😕

**Comment by gcaffa** [comment]
Same device (HP printer):
- First is using cmd.
- Second one is using pysnmp

![image](https://user-images.githubusercontent.com/82385829/214461148-a7a5f05d-6d5f-41d2-8c82-1646a33287f3.png)
![image](https://user-images.githubusercontent.com/82385829/214462543-62620b8b-6d98-4314-8214-cd94e5e8ba78.png)

Log file:
[error_pysnmp.log](https://github.com/lextudio/pysnmp/files/10495408/error_pysnmp.log)

It's also working with asyncio in other printer
![image](https://user-images.githubusercontent.com/82385829/214462369-6ad354d3-4baf-44e7-8cd9-53e21b519f31.png)

**Comment by lextm** [comment]
Hi @guidocaffa I deleted your log as it contains too much information than necessary.

You seem to hit a different issue based on its log entries that somehow for the problematic device it returns the last SNMP response message with a different request ID from the request sent by PySNMP. Once receiving such a response, PySNMP tried to recover from the differences and stopped.

It is one of the tough situations for any SNMP implementation to handle, so I don't think PySNMP is here to blame. The fix is to go deeper into your or your client's network to learn more about the problematic device and its behaviors. That might help identify the actual solution (such as replacing the device with a new model or upgrade its firmware). Sometimes you even need support services from the device vendor(s).

**Comment by gcaffa** [comment]
I was able to validate that indeed the device is not responding correctly to the getBulk method. Even with other tools. If I perform a getNext, it gets all the information.

Thank you!

**Comment by lextm** [comment]
Never mind. Most network issues like this are not easy to troubleshoot due to the varied nature.

Let's keep it open for a while.

**Comment by lextm** [comment]
Close this now. We might reopen it when new information becomes available.
