### ISSUE TITLE
can't reuse engine for snmpv3 when using UsmUserData usmKeyTypeLocalized in standard and asyncio modes, no issues with snmpv2

### ISSUE THREAD

**Issue by billross00** [lextudio/pysnmp#31]
using python 3.10.11 and pysnmp-lextudio 5.0.29
trying to re-use the same engine for multiple snmpget in order to make it quicker
I have both v2 and v3 devices.
My v3 devices use usmKeyTypeLocalized with a security name, authkey and privKey

Here is the code 
            usm_user_data = hlapi.UsmUserData(
                userName=sec,
                authKey=pysnmp.proto.rfc1902.OctetString(hexValue=auth),
                privKey=pysnmp.proto.rfc1902.OctetString(hexValue=priv),
                authKeyType=pysnmp.entity.config.usmKeyTypeLocalized,
                privKeyType=pysnmp.entity.config.usmKeyTypeLocalized,
                securityEngineId=pysnmp.proto.rfc1902.OctetString(hexValue='0000000000'),
            )
            errorIndication, errorStatus, errorIndex, varBinds = await hlapi.getCmd( # pysnmplib = tuple - seems ok with extra comma
                #hlapi.SnmpEngine(),
                engine, # need new one each time
                usm_user_data,
                transport,
                hlapi.ContextData(), # not sure what this does
                hlapi.ObjectType(hlapi.ObjectIdentity('SNMPv2-MIB', 'sysDescr', 0)), # works
            )

When I use a new engine each time I have no problem.
When I use the same engine the first snmpget works and all subsequent ones report a timeout.
I re use the same engine for all the snmpv2 and never have an issue.

I wrote code to do with asyncio and without.
I see the same behavior in both

I ran the non asyncio version with debug all enabled with 2 devices
I separated the output into 2 files called first and second
I have attached them here
[first.txt](https://github.com/lextudio/pysnmp/files/13310822/first.txt)
[second.txt](https://github.com/lextudio/pysnmp/files/13310823/second.txt)

Let me know if there is something I can try to debug this further.

**Comment by lextm** [comment]
The initial investigation shows the implementation of localized keys support currently in PySNMP is completely broken and wasn't properly done.

So, the related code needs to be replaced and that won't come quickly.
