### ISSUE TITLE
using timeout and retry 

### ISSUE THREAD

**Issue by mehrnazd** [lextudio/pysnmp#38]
previously, we could pass `timeout` and `retries` as parameters to the `UdpTransportTarget` in `getCmd`.
for example:
```
UdpTransportTarget(('demo.snmplabs.com', 161), timeout=8.0, retries=0)
```
but in the new function,`Slim.get`, the only parameters that can be passed are `address` and `port`. and of course, it raises an Error:
```
    errorIndication, errorStatus, errorIndex, varBinds = await slim.get(
  File "/lib/python3.10/site-packages/pysnmp/hlapi/asyncio/slim.py", line 108, in get
    return await getCmd(
  File "/lib/python3.10/site-packages/pysnmp/hlapi/asyncio/cmdgen.py", line 155, in getCmd
    vbProcessor.makeVarBinds(snmpEngine, varBinds), __cbFun,
  File "/lib/python3.10/site-packages/pysnmp/hlapi/varbinds.py", line 32, in makeVarBinds
    elif isinstance(varBind[0], ObjectIdentity):
TypeError: 'int' object is not subscriptable

```
my question is how to use timeout and reties in `Slim.get`. 

thanks

**Comment by lextm** [comment]
Thanks. The two arguments were not considered initially but added now in release 5.0.32.
