### ISSUE TITLE
[Bug]: example code seems to have typo, raises unexpected runtime exception

### ISSUE THREAD

**Issue by grant-allan-ctct** [lextudio/pysnmp#43]
### Expected behavior

After changing the [broadcast-agent-discovery.py](https://github.com/lextudio/pysnmp/blob/ce9a47686ffd0bbab867016814b77a9db9591b93/examples/v1arch/asyncore/manager/cmdgen/broadcast-agent-discovery.py) sample code so that it stopped after the first response, rather than timing out, I expected the function call to finish gracefully after receiving one response.

### Actual behavior

But a bug happened like this:
```
RuntimeError: No active exception to reraise
```
coming from [this line in the code](https://github.com/lextudio/pysnmp/blob/ce9a47686ffd0bbab867016814b77a9db9591b93/examples/v1arch/asyncore/manager/cmdgen/broadcast-agent-discovery.py#L104).

I think that the `else:` word should be `except:` instead, or pehaps `except BaseException:` would be even better.

Some other code examples seem to be similarly afflicted, e.g. `spoof-source-address.py`

### Detailed steps

The steps are:
- change the value of `maxNumberResponses` (on [this line](https://github.com/lextudio/pysnmp/blob/ce9a47686ffd0bbab867016814b77a9db9591b93/examples/v1arch/asyncore/manager/cmdgen/broadcast-agent-discovery.py#L31)) to 1
- run up the example on a network that has more than one SNMP-savvy device

### Python package information

5.0.33

### Operating system information

Windows 10

### Python information

3.11.7

**Comment by lextm** [comment]
All asyncore related bits are no longer supported as Python 3.x deprecated.

**Comment by grant-allan-ctct** [comment]
Interestingly (at least to me), I was using Python 3.11.7 at the time, and had no problem with this code once I changed the `else` to `except`.

**Comment by lextm** [comment]
asyncio was introduced in Python 3.4 and has been promoted to be the only option in 3.12. That's why there is no interest to keep asyncore related bits around.

If you are looking for an example with asyncio, you can find it in release5.0.35, 

https://github.com/lextudio/pysnmp/blob/v5.0.35/examples/v1arch/asyncio/manager/cmdgen/broadcast-agent-discovery.py

**Comment by grant-allan-ctct** [comment]
@lextm thank you!!  I tweaked my code so that it now mimics the asyncio example in Release 5.0.35, and it has turned out to be simpler code and yet still works just as well as before.  🏆
