### ISSUE TITLE
ignoreNonIncreasingOid for nextCmd

### ISSUE THREAD

**Issue by denisbondar** [lextudio/pysnmp#47]
Greetings!

I came across a lot of OLT BDCOM of GP3600 series and all of them have a common feature: Table `Q-BRIDGE-MIB::dot1qTpFdbTable` is indexed out of order, which leads to the error "OID not increasing".
Previously, [based on the documentation](https://www.pysnmp.com/pysnmp/faq/oids-not-increasing), there was an `ignoreNonIncreasingOid` option, which allowed you to ignore such behavior of the agent at your own risk. But this option is not available for asyncio.

Are there any plans to implement this feature for asyncio at least for the `nextCmd` method?

**Comment by denisbondar** [comment]
I found https://github.com/etingof/pysnmp/pull/364 PR on this subject in Ilya's repository.

**Comment by lextm** [comment]
Included in release 5.0.37.
