### ISSUE TITLE
[Bug]: cannot import name 'sync' from 'pysnmp.hlapi.asyncio'

### ISSUE THREAD

**Issue by dhopp97** [lextudio/pysnmp#52]
### Expected behavior

Importing pysnmp.entity.rfc3413.oneliner.cmdgen should succeed.

### Actual behavior

>>> import pysnmp.entity.rfc3413.oneliner.cmdgen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/test/lib/python3.11/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py", line 11, in <module>
    from pysnmp.hlapi.asyncio import sync
ImportError: cannot import name 'sync' from 'pysnmp.hlapi.asyncio' (/venv/test/lib/python3.11/site-packages/pysnmp/hlapi/asyncio/__init__.py)

### Detailed steps

Install latest pysnmp-lextudio (6.0.2) and try to import pysnmp.entity.rfc3413.oneliner.cmdgen

### Python package information

6.0.2

### Operating system information

Linux

### Python information

3.11.8

### (Optional) Contents of your test script

```python
import pysnmp.entity.rfc3413.oneliner.cmdgen
```

**Comment by dhopp97** [comment]
It looks like in 5.0.35 the `pysnmp/entity/rfc3413/oneliner/cmdgen.py` was modified to do 

```
from pysnmp.hlapi.asyncio import sync
```

instead of

```
from pysnmp.hlapi.asyncore import sync
```

However, I don't see a `sync` directory under `pysnmp/hlapi/asyncio`.  I do see it under `pysnmp/hlapi/asyncore`

**Comment by dhopp97** [comment]
I did see https://github.com/lextudio/pysnmp/issues/49 but it looks like the issue is different.

**Comment by lextm** [comment]
This is by design. All asyncore related bits are considered obsolete.

**Comment by dhopp97** [comment]
@lextm I understand that the asyncore bits are obsolete but this still seems like a bug (or more code needs to be cleaned up).  There is code that is importing `from pysnmp.hlapi.asyncio import sync` which doesn't exist in the project.

**Comment by lextm** [comment]
You got your code from the asyncore API, so not supporting it in release 6.0 isn't a bug.

BTW, all asyncore related parts have been deleted from the documentation. The only remaining API supported is the documented asyncio one. You can refer to https://pysnmp.com/pysnmp for more details.

**Comment by dhopp97** [comment]
All I'm saying is if it's not supported things like https://github.com/lextudio/pysnmp/blob/c756846b8ed6b29427b884361c74128ed43a37ed/pysnmp/entity/rfc3413/oneliner/cmdgen.py#L11 should be removed.  That is in the 6.0.2 code but whether the right thing to do is removing that entire .py file or not I'm not sure.

It was found because we have code that triggered that code path when we tried to upgrade to 6.0.2.  We can, and will, fix our code but it still seems odd to leave code that is definitely broken and not supported in the project.

**Comment by lextm** [comment]
It seems that you are using `CommandGenerator` and hit this issue. Since this type depends on asyncore, we don't intend to support it like that asyncore bits.

We will remove this type from docs as well.

**Comment by lextm** [comment]
BTW, in release 6.0.6 we are able to add some sync API back based on asyncio.

However, they are different from the legacy versions based on asyncore. And we still have no plan to bring oneliner back as it's also tightly coupled with asyncore.

**Comment by lextm** [comment]
Release 6.0.9 also brings back sync version of the oneliner API to support home-assistant project. home-assistant/core#112795

**Comment by lextm** [comment]
Due to issues like #64, the plan is to remove such sync methods in a future release.
