### ISSUE TITLE
[Bug]: IPv6 SNMP trap receiver receives IPv4 traps when using '::' as address

### ISSUE THREAD

**Issue by jaltendorfer** [lextudio/pysnmp#53]
### Expected behavior

When starting a IPv6 trap receiver with the address '::' all IPv6 traps and no IPv4 traps are received.

### Actual behavior

When starting a IPv6 trap receiver with the address '::' all IPv6 traps and IPv4 traps are received.
The IPv4 trap address is mapped to IPv6 (`::ffff:{ipv4-address}`).

### Detailed steps

```
from pysnmp.entity import engine, config
from pysnmp.carrier.asyncio.dgram import udp, udp6
from pysnmp.entity.rfc3413 import ntfrcv

snmpEngine = engine.SnmpEngine()

# UDP over IPv6
config.addTransport(
    snmpEngine, udp6.domainName, udp6.Udp6Transport().openServerMode(("::", 162))
)

# UDP over IPv4
config.addTransport(
    snmpEngine, udp.domainName, udp.UdpTransport().openServerMode(("127.0.0.1", 162))
)

config.addV1System(snmpEngine, "my-area", "public")

def cbFun(snmpEngine, stateReference, contextEngineId, contextName, varBinds, cbCtx):
    print(
        'Notification from ContextEngineId "{}", ContextName "{}"'.format(
            contextEngineId.prettyPrint(), contextName.prettyPrint()
        )
    )
    for name, val in varBinds:
        print(f"{name.prettyPrint()} = {val.prettyPrint()}")


# Register SNMP Application at the SNMP engine
ntfrcv.NotificationReceiver(snmpEngine, cbFun)

snmpEngine.transportDispatcher.jobStarted(1)  # this job would never finish

# Run I/O dispatcher which would receive queries and send confirmations
try:
    snmpEngine.transportDispatcher.runDispatcher()
except:
    snmpEngine.transportDispatcher.closeDispatcher()
    raise
```

In this example, I want to receive all IPv6 SNMP traps and IPv4 traps only on 127.0.0.1.
This does not work as we expect and we also receive all IPv4 SNMP traps (from other interfaces) in the format `::ffff:<ipv4-address>`.

### Python package information

6.0.4

### Operating system information

Linux

### Python information

3.11.7

**Comment by lextm** [comment]
This seems to be the limitation of `openServerMode` at this moment as it does not set `IPV6_V6ONLY` option by default.

Will see if allowing you to initialize the `socket` on your own helps.

**Comment by jaltendorfer** [comment]
This works perfectly, thank you for the fast fix.
