### ISSUE TITLE
[Bug]: Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by rebortg** [lextudio/pysnmp#58]
### Expected behavior

running without an error :-)

### Actual behavior

query more than one host in a row, will produce this warning:
```
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<AsyncioDispatcher.handle_timeout() running at /Users/rob/.local/share/virtualenvs/pysnmp_task_problem-7Bn0Zlyg/lib/python3.12/site-packages/pysnmp/carrier/asyncio/dispatch.py:62> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

i found an old stackoverflow post of the original maintainer about this, but no issue in original repo:
https://stackoverflow.com/questions/39265772/asyncio-task-was-destroyed-but-it-is-pending-in-pysnmp-sample-program

The fix he is providing does not work any more.

### Detailed steps

example script, which reproduce the error:
https://github.com/rebortg/pysnmp_task_problem/blob/main/example.py

### Python package information

6.1.2

### Operating system information

macOS

### Python information

3.11 and 3.12

**Comment by hluker** [comment]
+1 on this, I'm not using the specific script provided here, but something pretty similar and trying to figure out how to plug these errors. My script works fine, just generates a lot of these errors in the log file.

**Comment by lextm** [comment]
For us, the error only occurred in a few test cases, such as https://github.com/lextudio/pysnmp/blob/v6.1.2/tests/hlapi/asyncio/manager/cmdgen/test_v1_get.py#L152. We are investigating internally to see how to resolve it quickly.

@hluker @rebortg Can you also do the following check? As [documented here](https://docs.lextudio.com/pysnmp/upgrade#upgrade-to-6-x), PySNMP 6.1 only works with PySMI 1.3 and above, and you also need to recompile all MIB documents using the newer PySMI version. That alone should eliminate quite a few such errors.

**Comment by lextm** [comment]
@rebortg We thought this might be a known issue we are investigating internally, but it turns out to be a mistake in your sample code.

`SnmpEngine` is a resource that manages quite a few tasks under the hood, so like what we showed in most examples you need to explicitly free up them by calling `SnmpEngine.transportDispatcher.closeDispatcher()`.

Without that such error messages will occur and the signature is the `wait_for=<Future pending cb=...` portion. The tasks were pending and would be only cancelled by `closeDispatcher`.

**Comment by lextm** [comment]
@hluker Not sure if you hit exactly the same issue, so please review the actual error messages in your log file. If they all contain `wait_for=<Future pending cb=...`, then likely your code has the same mistake.

If yours contain things like `wait_for=<Future cancelled>`, please open a new issue and provide more details.

**Comment by lextm** [comment]
@rebortg In your case, the message changes to `wait_for=<Future cancelled>` which is almost harmless.

WALK operation by nature generates too many resources under the hood and `closeDispatcher()` already cancelled them. It seems to us that it might take the Python runtime too long to fully clean up the mess and such an error message is logged.

The one we tracked internall is different from yours.

**Comment by hluker** [comment]
Diddo, thanks for the quick response. Adding the `engine.transportDispatcher.closeDispatcher()` line fixed things for me, though likewise still have the `wait_for=<Future cancelled>` message as described above. I suppose I will just ignore it. Thanks!

**Comment by rebortg** [comment]
@hluker i do the same at the moment with:

```
import logging
logging.getLogger('asyncio').setLevel(logging.CRITICAL)
```

**Comment by lextm** [comment]
@rebortg just noticed that you don't need to suppress logging (which might hide other critical issues from your eyes). Maybe just calling `asyncio.get_event_loop().close()` which frees up the loop and all associated tasks.
