### ISSUE TITLE
walkCmd does not return

### ISSUE THREAD

**Issue by WakkaTrout** [lextudio/pysnmp#64]
### Expected behavior

I expected the generator returned from the pysnmp hlapi walkCmd specified here https://docs.lextudio.com/pysnmp/docs/hlapi/asyncio/sync/manager/cmdgen/walkcmd to return a tuple when calling next() as demonstrated in the example

### Actual behavior

However, when I actually call next() on the generator, the system hangs and no tuple is returned. I wiresharked the interface and am seeing the managed device return the proper snmpv3 packet in response to the sent snmpv3 command, but the pysnmp library seems to be losing the packet somehow

### Detailed steps

I attempted to use the next on the walkCmd as specified here https://docs.lextudio.com/pysnmp/docs/hlapi/asyncio/sync/manager/cmdgen/walkcmd on tables defined in custom python MIBs I generated using pysmi's mibdump tool.

I have placed the generated MIB's in my linux home directory here ~/.pysnmp/mibs

I called walkCmd as done in the test script below.

The only way to break out of the hang was to ctrl+C and it seems that it was stuck in asyncio calling select.

### Python package information

6.1.2 (but I also experienced it in 6.0.11)

### Operating system information

Linux RHEL 8

### Python information

python 3.11

### (Optional) Contents of your test script

```python
engine = SnmpEngine()
credentials = UsmUserData(...)
target = UdpTransportTarget((ipaddress, 161))
oids = [ObjectType(ObjectIdentity(...)),...]
iterator = walkCmd(engine, credentials, target, ContextData(), oids*, lexicographicMode=False)

# It hangs in the first iteration here->(never enters the loop body)
for error_indication, error_status, error_index, var_bind in iterator:
    ....
```

**Comment by lextm** [comment]
PySNMP can drop incoming messages for many reasons, so you need to troubleshoot first,

https://docs.lextudio.com/pysnmp/troubleshooting.html

**Comment by lextm** [comment]
In the past few weeks we actually submitted the changes to a few downstream projects with more audience, and we believe `walkCmd` is a reliable implementation (and we reused most of the code from Ilya). So we won't be able to pursue troubleshooting on a specific device of you.

If you do need further assistance, you can write to support@lextudio.com to open a support case.

**Comment by mjbogusz** [comment]
I have encountered this behavior as well, though in a slightly different context/usage pattern.

For me `walkCmd` and `bulkWalkCmd` both result in a lockup with analogous message in debug logs (`sendPdu: sendPduHandle`), if run in more than one asyncio loop (e.g. via `asyncio.run()`). I've encountered this first when running the commands directly from `pysnmp.hlapi`, and then narrowed it down when manually wrapping `pysnmp.hlapi.asyncio` commands with `asyncio.run()`.

As far as understand the whole asyncio stack and what the library does in the background, it seems that pysnmp doesn't clear or end some background tasks.

Below I'm including a complete test program that I've extracted from my program - while not minimal, it should be a reproducible example. By default it queries a host for it's interface ports' statues (ifOperStatus from IF-MIB) - in my case I'm pointing it at a Mikrotik switch. It can run in 2 modes - default "synchronous" calling `asyncio.run()` twice, simulating my usecase of synchronizing the calls; or "asynchronous" via a switch running `walkCmd` twice in one `asyncio.run()`, simulating whole asyncio-based project.

The expected behavior is that both modes finish cleanly and result in the same output; the observer behavior is that the "synchronous" version hangs.

<details><summary>Test program (click here to fold/unfold)</summary>
<p>

```python
#!/usr/bin/env python3
import asyncio
import time
import argparse

from pysnmp import hlapi, debug
from pysnmp.hlapi.asyncio import walkCmd


async def walk(engine: hlapi.SnmpEngine, transport: hlapi.UdpTransportTarget, oids: list[str]):
    var_binds_in = [hlapi.ObjectType(hlapi.ObjectIdentity(oid)) for oid in oids]
    bulk_generator = walkCmd(
        engine,
        hlapi.CommunityData('public'),
        transport,
        hlapi.ContextData(),
        *var_binds_in,
        lookupMib=False,
        lexicographicMode=False,
    )
    snmp_result = []
    async for (error_indication, error_status, error_index, var_binds) in bulk_generator:
        if error_indication:
            raise RuntimeError('error_indication')
        if error_status:
            raise RuntimeError('error_status')
        snmp_result += list(var_binds)
    return snmp_result


async def a_test(engine: hlapi.SnmpEngine, transport: hlapi.UdpTransportTarget, oids: list[str]):
    snmp_result = await walk(engine, transport, oids)
    print('snmp_result:', snmp_result)
    await asyncio.sleep(1)

    snmp_result = await walk(engine, transport, oids)
    print('snmp_result2:', snmp_result)


def test(engine: hlapi.SnmpEngine, transport: hlapi.UdpTransportTarget, oids: list[str]):
    snmp_result = asyncio.run(walk(engine, transport, oids))
    print('snmp_result:', snmp_result)
    time.sleep(1)

    snmp_result = asyncio.run(walk(engine, transport, oids))
    print('snmp_result2:', snmp_result)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--host', default='localhost')
    parser.add_argument('--port', default=161, type=int)
    parser.add_argument('--oids', nargs='+', default=['1.3.6.1.2.1.2.2.1.8'])
    parser.add_argument('--debug', action='store_true')
    parser.add_argument('--asynchronous', action='store_true')
    args = parser.parse_args()

    if args.debug:
        debug.setLogger(debug.Debug('all'))
    engine = hlapi.SnmpEngine()
    transport = hlapi.UdpTransportTarget(transportAddr=(args.host, args.port), timeout=1, retries=0)

    if args.asynchronous:
        asyncio.run(a_test(engine, transport, args.oids))
    else:
        test(engine, transport, args.oids)


if __name__ == '__main__':
    main()
```
</p>
</details>

**Comment by mjbogusz** [comment]
@WakkaTrout could you verify my findings with the program I've included above?
@lextm would you consider reopening the issue until the root cause is found and there's either a fix or a correct usage example posted?

**Comment by lextm** [comment]
@mjbogusz your report might be related to #78.

**Comment by mjbogusz** [comment]
It is quite likely to be related, but I'm not using multithreading in my test program and my output and observed behavior match almost exactly what was posted here.
If you see any incorrect usage of the library in said program please point it out, I might as well have misunderstood the docs.

**Comment by WakkaTrout** [comment]
@mjbogusz I can confirm that with my device, the test program works with the async a_test and hangs with the same behavior I normally see with the non-async test. 

Aside: I had to modify the test to use SNMPv3 as my device only supports that, but the rest of the setup was equivalent

**Comment by tomoum** [comment]
i believe i found the problem at least in my case which is i was importing things from the wrong place it seems i was using the snmp engine and context data from the `pysnmp.hlapi` while i should have been using it from `pysnmp.hlapi.asyncio.sync.cmdgen` so when i changed my imports to this everything works. I think the library should probably throw an error to say hey you are using the wrong thing here. anyways i hope this helps someone out there.  

FIX:
walkCmd doesnt hang forever and works as expected.

`from pysnmp.hlapi import ObjectIdentity, UdpTransportTarget
from pysnmp.hlapi.asyncio.sync.cmdgen import (
    ContextData,
    ObjectType,
    SnmpEngine,
    bulkCmd,
    bulkWalkCmd,
    getCmd,
    nextCmd,
    setCmd,
    walkCmd,
)
`

**Comment by lextm** [comment]
@tomoum That is a nice catch.

But you should notice that the sync API surface has been completely removed in the 6.2 release, so you will have to fully migrate to the remaining asyncio-based async API surface instead.

**Comment by lextm** [comment]
Lock this thread, as the sync API is deprecated.
