### ISSUE TITLE
[Bug]: AttributeError: 'SnmpEngine' object has no attribute 'openDispatcher'

### ISSUE THREAD

**Issue by Omid888** [lextudio/pysnmp#71]
While following the official examples, [_**from here**_](https://docs.lextudio.com/pysnmp/examples/v3arch/asyncio/agent/cmdrsp/snmp-versions), (which is expected to be a working code) 2 errors were occurred:

```
Traceback (most recent call last):
  File "/Users/ata/PycharmProjects/snmp-lextudio/main.py", line 102, in <module>
    snmpEngine.openDispatcher()
AttributeError: 'SnmpEngine' object has no attribute 'openDispatcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ata/PycharmProjects/snmp-lextudio/main.py", line 104, in <module>
    snmpEngine.closeDispatcher()
AttributeError: 'SnmpEngine' object has no attribute 'closeDispatcher'
```

Note: As I noticed, all the examples in this repo are subject to this problem.

### Python package information

pysnmp-lextudio==6.1.2

### Operating system information

mac os

### Python information

3.8

**Comment by mtellese** [comment]
From what I gather its a depreciated functionality that just hasn't been updated. They do note on the website that much of the examples are old and likely outdated.
