### ISSUE TITLE
[Bug]: Can't run snmpresponderd after pip install 

### ISSUE THREAD

**Issue by danielsvicente** [lextudio/pysnmp#73]
### Expected behavior

Expected to be able to run snmpresponder after installing the package.

### Actual behavior

Application is not found. Apparently it is not being installed properly.

### Detailed steps

I installed snmpresponder on Ubuntu using pip install.
Then tried to run the application by running 'snmpresponderd --help' following the instructions in https://docs.lextudio.com/snmpresponder/

### Python package information

0.0.3

### Operating system information

Linux Ubuntu 22.04

### Python information

3.12.3

**Comment by lextm** [comment]
Should have been fixed in the 0.0.5 release. However, this utility is of low priority on our list.
