### ISSUE TITLE
broadcast-agent-discovery - supporting multiple network interfaces

### ISSUE THREAD

**Issue by stuartlynne** [lextudio/pysnmp#74]
I am working with the broadcast-agent-discover.py script and that is working well, but only with a single network interface.

The network environment I need to support has (at least) two active network interfaces, and I need to discover devices in both.

I have tried variations of the suggestion in this page with no luck: https://pysnmp.readthedocs.io/en/latest/faq/listening-on-multiple-interfaces.html.

When the second network is active the script still finds the devices in the main network, but does not see devices in the second.

Looking for pointers on what needs to be added.

Thanks!

**Comment by lextm** [comment]
1. `https://pysnmp.readthedocs.io` is an invalid site and we don't cover anything it says in this repo.
2. If your OS/network stack doesn't like `255.255.255.255` to broadcast on both networks, you might try to broadcast to either of them with the right broadcast address and then combine the results.
