### ISSUE TITLE
[Bug]: Synchronous API fails if run in thread context

### ISSUE THREAD

**Issue by kroeschl** [lextudio/pysnmp#78]
### Expected behavior

The [synchronous API](https://github.com/lextudio/pysnmp/blob/v6.1.2/pysnmp/hlapi/asyncio/sync/cmdgen.py) (`pysnmp.hlapi.getCmd` and friends) should function when run in a thread or other contexts which may not have a running event loop.

### Actual behavior

When running e.g. `getCmd` in a thread, I see the following error:
```
Exception in thread Thread-1 (get):
Traceback (most recent call last):
  File ".../python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File ".../python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File ".../repro.py", line 10, in get
    pysnmp.hlapi.getCmd(
  File ".../python3.12/site-packages/pysnmp/hlapi/asyncio/sync/cmdgen.py", line 97, in getCmd
    loop = asyncio.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.12/asyncio/events.py", line 702, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (get)'.
```

### Detailed steps

Here's a simple reproducing script:
```python
import threading

import pysnmp.hlapi
import pysnmp.hlapi.asyncio


def get():
    ip = "10.0.122.191"
    oid = "1.3.6.1.4.1.318.1.1.4.4.2.1.3.7"
    pysnmp.hlapi.getCmd(
        pysnmp.hlapi.SnmpEngine(),
        pysnmp.hlapi.CommunityData("private"),
        pysnmp.hlapi.UdpTransportTarget((ip, 161)),
        pysnmp.hlapi.ContextData(),
        pysnmp.hlapi.ObjectType(pysnmp.hlapi.ObjectIdentity(oid), pysnmp.hlapi.Integer(0)),
    )
    print("Complete")


get()
x = threading.Thread(target=get)
x.start()
x.join()
```

I'm working around this right now by just using the async API via
```python
asyncio.run(pysnmp.hlapi.asyncio.getCmd(...))
```

### Python package information

6.1.2

### Operating system information

Debian 13, Windows 10

### Python information

Python 3.8.12, 3.9.13, 3.12.4

**Comment by lextm** [comment]
The primary goal to introduce those sync methods was to enable quick migration to 6.x releases, but we don't feel the current PySNMP code base was well designed with all asyncio best practices.

The current plan to retire the sync version of those methods in a future release, so people are suggested to fully migrate to the async version.

**Comment by lextm** [comment]
We decided to retire all sync API based on asyncio in release 6.2, and no longer pursue on a solution here.

If you intend to use asyncio based async API in sync pattern, that's your tasks now and you should build your own wrapper.
