### ISSUE TITLE
[Bug]:  ModuleNotFoundError: No module named 'pysnmp.carrier.asynsock

### ISSUE THREAD

**Issue by theodore86** [lextudio/pysnmp#84]
### Expected behavior

I expected to be able to import the module

### Actual behavior

 ModuleNotFoundError: No module named 'pysnmp.carrier.asynsock

### Detailed steps

pip install pysnmp (latest)

### Python package information

6.2.2

### Operating system information

Linux

### Python information

3.10.9/3.11.9

**Comment by lextm** [comment]
Anything related to asynsock/asyncore has been removed. You need to use the types from asyncio related modules.

**Comment by theodore86** [comment]
i am using this library as dependency from SnmpLibrary https://github.com/kontron/robotframework-snmplibrary

**Comment by lextm** [comment]
Please fork that project and make the edits yourself.
