### ISSUE TITLE
PySMI Json Output being Alphabetized

### ISSUE THREAD

**Issue by gfidder** [lextudio/pysnmp#97]
### Expected behavior

In an older version of PySMI, when using the mibdump.py script, the order of the json output of a MIB was the same order as the original MIB contents

[SNMPv2-TC_expected.json](https://github.com/user-attachments/files/16677684/SNMPv2-TC_expected.json)

### Actual behavior

The json output of the MIB has everything alphabetized by key when using the jinja `mib|tojson` method rather than order of the original MIB

[SNMPv2-TC_actual.json](https://github.com/user-attachments/files/16677689/SNMPv2-TC_actual.json)

When debugging, it was noticed that the mib dictionary was the correct order we expected, but the output is alphabetized.

### Detailed steps

Generate a mibdump with a json output with an older version of pysmi (0.3.4):
`python mibdump.py --mib-source ../mib/location --destination-directory ../some/directory --destination-format json SNMPv2-TC`

Generate a mibdump with a json output with the current version of pysmi:
`python mibdump.py --keep-text-layout --mib-source ../mib/location --destination-directory ../some/directory --destination-format json SNMPv2-TC`

### Python package information

1.4.3

### Operating system information

Windows

### Python information

3.11

**Comment by lextm** [comment]
Currently no plan to address this.
