### ISSUE TITLE
Missing tag for snmpclitools 0.7.1

### ISSUE THREAD

**Issue by teeks99** [lextudio/pysnmp#98]
### Expected behavior

First: Submitting here because issues aren't enabled on the `snmpclitools` repo and the link from the readme for reporting issues links here.

There is not a tag in the `snmpclitools` repo that matches the 0.7.1 version that is uploaded to PyPI. It might also be worth making a note in the old `snmpclitools-lextudio` package on PyPI to go back to the original `snmpclitools` package.

### Actual behavior

Can't trace from the package to a specific commit.

### Detailed steps

View tags in git.

### Python package information

0.7.1

### Operating system information

N/A

### Python information

N/A

**Comment by lextm** [comment]
Thanks for the report, and the tag has been added.

Another way to locate the commit is to check the commit message, as we always use "Bumped the version" to manually update the version and release notes.
